name: real_shelf_traj_pcd

image_shape: [3, 96, 128] # [channel, height, width]
depth_shape: [480, 640] # [height, width]
pcd_shape: [6, 2000] # [channel:(x,y,z,r,g,b), number of points]
dataset_path: data/real_shelf

action_bound:
  x_lower: None
  x_upper: None
  y_lower: None
  y_upper: None
  z_lower: None
  z_upper: None

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # camera_0_color:
    #   shape: ${task.image_shape}
    #   type: rgb
    # camera_4_color:
    #   shape: ${task.image_shape}
    #   type: rgb
    point_cloud:
      shape: ${task.pcd_shape}
      type: spatial
      info:
        view_keys:
          # - camera_0
          # - camera_1
          - camera_2
          # - camera_3
          - camera_4
          - camera_5
        boundaries:
          x_lower: -0.1
          x_upper: 0.35
          y_lower: -1
          y_upper: 0.0
          z_lower: 0.35
          z_upper: 0.9
        reference_frame: world
        resize_ratio: 0.5
        voxel_size: 0.003
        left_tool: soft_hande
        right_tool: soft_hande
        rob_pcd: false
        N_joints: 3
        N_per_link: 50
        eef_pcd: true
        N_eef: 200 
        ee_color: [0.5, 1.0, 0]
    robot_joint:
      shape: [14]
      type: low_dim
    robot_ft_wrench:
      shape: [12]
      type: low_dim

  action:
    shape: [14]
    type: joint_action  # cartesian_action or joint_action

env_runner:
  _target_: diffusion_policy.env_runner.real_pcd_runner.RealPcdRunner

dataset:
  _target_: diffusion_policy.dataset.real_pcd_dataset.RealPcdDataset
  shape_meta: *shape_meta  
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.1
  max_train_episodes: null
  delta_action: False
  debug_overfit: False
  debug: ${debug}
  use_robomimic_legacy_normalizer: True


