name: transport_lowdim

obs_dim: 69 # 41+(3+4+2)*2
action_dim: 20 # 10*2
keypoint_dim: 3
num_agents: 1

obs_keys: &obs_keys [
  'robot0_eef_pos', 'robot1_eef_pos',
  'object', 
  'robot0_eef_quat', 'robot0_gripper_qpos', 
  'robot1_eef_quat', 'robot1_gripper_qpos'
]
task_name: &task_name transport
dataset_type: &dataset_type mh
dataset_path: &dataset_path data/robomimic/datasets/${task.task_name}/${task.dataset_type}/low_dim_abs.hdf5
abs_action: &abs_action True


# Configuration based on robomimic paper
# Reference: https://arxiv.org/pdf/2108.03298.pdf
obj_pos_idx: &obj_pos_idx
  - [0, 3]   # absolute position and quaternion of the hammer 
  - [7, 10]  # absolute position of the trash cube
  - [14, 17] # absolute position of the lid handle 
  - [21, 24] # the target bin position
  - [24, 27] # the trash bin position 
  - [27, 33] # the relative positions of the hammer and the lid handle with respect to the first arm end effector
  - [33, 39] # the relative positions of the hammer and trash cube with respect to the second arm end effector

obj_quat_idx: &obj_quat_idx
  - [3, 7]   # absolute quaternion of the hammer 
  - [10, 14] # absolute quaternion of the trash cube
  - [17, 21] # absolute quaternion of the lid handle

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_lowdim_runner.RobomimicLowdimRunner
  dataset_path: *dataset_path
  obs_keys: *obs_keys
  obj_pos_idx: *obj_pos_idx
  obj_quat_idx: *obj_quat_idx
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  max_steps: 700
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  render_hw: [128,128]
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  n_envs: 28
# evaluation at this config requires a 16 core 64GB instance.
  visualize_state_denoising: False

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_lowdim_dataset.RobomimicReplayLowdimDataset
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  obs_keys: *obs_keys
  abs_action: *abs_action
  obj_pos_idx: *obj_pos_idx
  obj_quat_idx: *obj_quat_idx
  use_legacy_normalizer: False
  seed: 42
  val_ratio: 0.02
