defaults:
  - _self_
  - task: mimicgen_abs

name: equi_diff
_target_: equi_diffpo.workspace.train_equi_workspace.TrainEquiWorkspace

shape_meta: ${task.shape_meta}
exp_name: "default"


num_epochs: 200
n_demo: 100
batch_size: 64
num_workers: 8
debug: False


task_name: stack_d1

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
dataset: equi_diffpo.dataset.robomimic_replay_image_sym_dataset.RobomimicReplayImageSymDataset
data_dir: /scratch/jx30
dataset_path: ${data_dir}/data/robomimic/datasets/${task_name}/${task_name}_abs.hdf5

policy:
  _target_: equi_diffpo.policy.diffusion_equi_unet_cnn_enc_policy.DiffusionEquiUNetCNNEncPolicy

  shape_meta: ${shape_meta}
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small # Yilun's paper uses fixed_small_log instead, but easy to cause Nan
    clip_sample: True # required when predict_epsilon=False
    prediction_type: epsilon # or sample

  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 100
  crop_shape: [76, 76]
  # crop_shape: null
  diffusion_step_embed_dim: 128
  enc_n_hidden: 128
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True
  rot_aug: False

  # scheduler.step params
  # predict_epsilon: True

ema:
  _target_: equi_diffpo.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: ${batch_size} #128
  num_workers: ${num_workers} #8
  shuffle: True
  pin_memory: True
  persistent_workers: True
  drop_last: true

val_dataloader:
  batch_size: ${batch_size} #128
  num_workers: ${num_workers} #8
  shuffle: False
  pin_memory: True
  persistent_workers: True

optimizer:
  betas: [0.95, 0.999]
  eps: 1.0e-08
  learning_rate: 0.0001
  weight_decay: 1.0e-06

training:
  device: "cuda:0"
  seed: 0
  debug: ${debug}
  resume: True
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: ${num_epochs}
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  # training loop control
  # in epochs
  rollout_every: 10
  checkpoint_every: 20
  val_every: 10
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: diffusion_policy_${task_name}
  resume: True
  mode: online
  name: equidiff_demo${n_demo}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: ${data_dir}/data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: ${data_dir}/data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: ${data_dir}/data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
