defaults:
  - _self_
  - task: real_laundry_traj_pcd

name: train_diffusion_traj_unet3d_real_vae_pcd_workspace
_target_: diffusion_policy.workspace.train_diffusion_unet_pcd_workspace.TrainDiffusionUnetPcdWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"
debug: True

horizon: 16
n_obs_steps: 2
n_action_steps: 4
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_impainting: False
obs_as_global_cond: True
diffuse_action: False
epochs_waited_before_next_stage: 5
max_epochs_without_improvement: 20
batch_size: 32

resume_dir: null

policy:
  _target_: diffusion_policy.policy.diffusion_traj_unet3d_vae_pcd_policy.DiffusionTrajUnet3dVaePcdPolicy

  shape_meta: ${shape_meta}
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: learned_range # learned_range, learned, fixed_small
    clip_sample: True # required when predict_epsilon=False
    prediction_type: epsilon # or sample

  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 100
  obs_as_global_cond: ${obs_as_global_cond}
  obs_as_impainting: ${obs_as_impainting}
  crop_shape: [76, 76]
  # crop_shape: null
  diffusion_step_embed_dim: 128
  down_dims: [512, 1024, 2048]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True
  obs_encoder_group_norm: True
  eval_fixed_crop: True
  variance_type: ${policy.noise_scheduler.variance_type}
  schedule_sampler: loss-second-moment # uniform, loss-second-moment
  vb_factor: 0.01
  input_pertub: 0.1
  sample_temperature: 0.5
  inv_factor: 0.5
  inv_model_include_agent_info: True
  skip_inv_model: False
  n_his_inv: 1
  n_fut_inv: 2
  deno_state_only: True
  feat_proc: distill # none, linear, mlp, distill
  rgb_latent_dim: 64
  pcd_latent_dim: 64
  pn_net_cls: PointNet2Encoder  # PointNet2Encoder, PointNetAttnEncoder, CAMPointNetEncoder
  training_stage: 0
  tool_name: ${task.shape_meta.obs.point_cloud.info.left_tool}
  vae_latent_dim: 64
  loss_type: 'l2'

  # scheduler.step params
  # predict_epsilon: True

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: ${batch_size}
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: ${batch_size}
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: ${debug}
  resume: True
  # optimization
  lr_scheduler: cosine
  lr_warmup_steps: 500
  num_epochs: 3050
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: True
  # training loop control
  # in epochs
  rollout_every: 10
  checkpoint_every: 10
  val_every: 1
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  tqdm_interval_sec: 1.0

logging:
  project: diffusion_policy_debug
  resume: True
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_action_mse_error
    mode: min
    k: 5
    format_str: 'epoch={epoch:04d}-stage={stage:d}-action_mse={train_action_mse_error:.3f}.ckpt'

  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}

